version: '3'
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    image: keerthan11c/timecapsule-backend:latest
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/timecapsule
    depends_on:
      - mongo

  frontend:
    image: keerthan11c/timecapsule-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo-data: