version: '2'
services:

  backend:
    build: ./backend
    image: keerthan11c/timecapsule-backend:latest
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://keerthan11c:pyAU2loXgXuMjDI3@devops.olckxah.mongodb.net/timecapsule?retryWrites=true&w=majority&appName=devops
      - JWT_SECRET=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZjI4OTI5ZjBiZDBjNTM3YWJkZmYxYyIsImlhdCI6MTc0Mzk1OTUyMSwiZXhwIjoxNzQ0NTY0MzIxfQ.XQyBzjMz3Kpmh9UAupzflVIB6ayMFQd_4A8L6h3l6U0

  frontend:
    image: keerthan11c/timecapsule-frontend:latest
    ports:
      - "80:80"
    environment:
      - REACT_APP_BACKEND_URI=http://backend:5000
    depends_on:
      - backend