version: '3'
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    image: timecapsule-backend
    restart: always
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/timecapsule

volumes:
  mongo-data: